sudo: false # faster builds
os:
  - linux
language: java
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
jdk:
  - openjdk15
script: "mvn clean verify sonar:sonar -Dsonar.organization=thiagoteixeira-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN"
