server:
  port: 8081

spring:
  application:
    name: json-diff-business-service

microservices:
  data:
    uri: http://localhost:8082/v1/diff/{id}

rest:
  http:
    maxConnections: 100
    maxConnPerRoute: 100
    readTimeout: 60000
    connectionTimeout: 1000